module Fishbowl; module Requests; end; end

require 'fishbowl/requests/add_inventory'
require 'fishbowl/requests/add_sales_order_item'
require 'fishbowl/requests/adjust_inventory'
require 'fishbowl/requests/get_carrier_list'
require 'fishbowl/requests/get_customer_list'
require 'fishbowl/requests/get_parts'
require 'fishbowl/requests/get_product'
require 'fishbowl/requests/get_customer'
require 'fishbowl/requests/import'
require 'fishbowl/requests/get_export_list'
require 'fishbowl/requests/export'
require 'fishbowl/requests/get_total_inventory'
require 'fishbowl/requests/get_import_list'
require 'fishbowl/requests/get_vendor_name_list'
require 'fishbowl/requests/get_next_number'
require 'fishbowl/requests/get_uom_list'
require 'fishbowl/requests/get_sales_order'
require 'fishbowl/requests/save_sales_order'
require 'fishbowl/requests/void_sales_order'
require 'fishbowl/requests/get_account_list'
require 'fishbowl/requests/delete_sales_order'
require 'fishbowl/requests/print_report'